UpdateBundle\Entity\DeviceInfo:
    type: entity
    table: null
    repositoryClass: UpdateBundle\Repository\DeviceInfoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: string
            length: 255
            unique: true
        productName:
            type: string
            length: 255
        channel:
            type: string
            length: 255
        appVersion:
            type: string
            length: 255
        innerVersion:
            type: string
            length: 255
        localVersion:
            type: string
            length: 255
        osVersion:
            type: string
            length: 255
        model:
            type: string
            length: 255
        device:
            type: string
            length: 255
        memory:
            type: string
            length: 255
        screenSize:
            type: string
            length: 255
        netState:
            type: string
            length: 255
        country:
            type: string
            length: 255
        language:
            type: string
            length: 255
        processInfo:
            type: text
    lifecycleCallbacks: {  }
