<?php

namespace UpdateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceInfoRepository extends EntityRepository
{
}
