<?php

namespace UpdateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UpdateInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateInfoRepository extends EntityRepository
{
}
