<?php

namespace UpdateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UpdateConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateConfigRepository extends EntityRepository
{
}
